#pragma once

#include "traits.h"

namespace MOGSLib { namespace RTS {

/**
 *  @class OpenMP
 *  @brief Abstraction of the OpenMP runtime system functionalities, types and API.
 */
struct OpenMP {

  /// @brief Id type is defined by an external Traits structure.
  using Id = typename Traits::Id;
  /// @brief Load type is defined by an external Traits structure.
  using Load = typename Traits::Load;

  static Id chunks;
  static Id pus;

  /**
   *  @brief Set the amount of chunks generated by the OpenMP runtime.
   *  @param nchunks The amount of chunks.
   *
   *  This method is designed to be called from within the OpenMP runtime.
   */
  static inline void nchunks(decltype(chunk_size) nchunks) { chunks = nchunks; }

  /**
   *  @brief Set the amount of threads generated by the OpenMP runtime.
   *  @param nthreads The amount of running threads managed by OpenMP.
   *
   *  This method is designed to be called from within the OpenMP runtime.
   */
  static inline void nthreads(decltype(nPEs) nthreads) { pus = nthreads; }
};

}}