#pragma once

#ifdef LINKED_TO_OMP

#include <abstractions/rts_representation.h>

#include <system/static.h>

BEGIN_NAMESPACE(Abstraction)

/**
 * @brief The declaration of a specific data structure to represent the OpenMP runtime system.
 * @details This structure must contain solely static data in order to be acessed globally by Binders, Initializers, Concepts and Adaptors.
 */
template<>
struct RTS<RuntimeSystemEnum::OpenMP> {  
  static unsigned chunk_size = 0;

  /**
   * @brief Define the amount of chunks that are generated by OpenMP.
   * @param nchunks The amount of chunks that are generated by OpenMP.
   */
  static inline void set_chunk_size(decltype(chunk_size) nchunks) { chunk_size = nchunks; }
};

END_NAMESPACE

#endif